kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: c2
networking:
  podSubnet: "10.20.0.0/16"
  serviceSubnet: "10.255.20.0/24"
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30001
        hostPort: 30001
        protocol: TCP
  - role: worker
